const Content = [
  {
    id: "intro",
    title: "Introduce",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.",
  },
  {
    id: "services",
    title: "Services",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.",
  },
  {
    id: "contact",
    title: "Contact",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.",
  },
  {
    id: "help",
    title: "Help",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto. Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium neque rerum, perferendis dolorum quia ducimus? Nostrum quia, quis, mollitia voluptate quae neque dicta quidem quo qui, necessitatibus a delectus iusto.",
  },
];
export default Content;
